{% set version = "1.0-7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-propagate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/propagate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/propagate/propagate_{{ version }}.tar.gz
  sha256: 7fdd9ea33b35fd9c6aa56befbe79f8a9f3e675d8c42d26155438c1bf8ee52b48

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-rcpp >=0.10.1
    - r-ff
    - r-minpack.lm
    - r-tmvtnorm
  run:
    - r-base
    - r-mass
    - r-rcpp >=0.10.1
    - r-ff
    - r-minpack.lm
    - r-tmvtnorm

test:
  commands:
    - $R -e "library('propagate')"           # [not win]
    - "\"%R%\" -e \"library('propagate')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=propagate
  license: GPL-2.0-or-later
  summary: Propagation of uncertainty using higher-order Taylor expansion and Monte Carlo simulation.
    Calculations of propagated uncertainties are based on matrix calculus including
    covariance structure according to Arras 1998 <doi:10.3929/ethz-a-010113668> (first
    order), Wang & Iyer 2005 <doi:10.1088/0026-1394/42/5/011> (second order) and BIPM
    Supplement 1 (Monte Carlo) <doi:10.59161/JCGM101-2008>.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - khughitt

# Package: propagate
# Type: Package
# LazyLoad: no
# LazyData: no
# Title: Propagation of Uncertainty
# Version: 1.0-6
# Date: 2018-05-02
# Author: Andrej-Nikolai Spiess <a.spiess@uke.uni-hamburg.de>
# Maintainer: Andrej-Nikolai Spiess <a.spiess@uke.uni-hamburg.de>
# Description: Propagation of uncertainty using higher-order Taylor expansion and Monte Carlo simulation.
# License: GPL (>= 2)
# Depends: R (>= 2.13.0), MASS, tmvtnorm, Rcpp (>= 0.10.1), ff, minpack.lm
# LinkingTo: Rcpp
# NeedsCompilation: yes
# Packaged: 2018-05-06 09:00:48 UTC; ans
# Repository: CRAN
# Date/Publication: 2018-05-06 17:08:12 UTC
